from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(905, 824)
        font = QtGui.QFont()
        font.setPointSize(14)
        Dialog.setFont(font)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=Dialog)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 902, 631))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setHorizontalSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setContentsMargins(20, -1, 20, -1)
        self.formLayout_2.setSpacing(20)
        self.formLayout_2.setObjectName("formLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_3)
        self.password = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.password.setEchoMode(QtWidgets.QLineEdit.EchoMode.Password)
        self.password.setObjectName("password")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.password)
        self.label_7 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_7)
        self.passwordPower = QtWidgets.QProgressBar(parent=self.gridLayoutWidget)
        self.passwordPower.setProperty("value", 0)
        self.passwordPower.setObjectName("passwordPower")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.passwordPower)
        self.gridLayout.addLayout(self.formLayout_2, 2, 2, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setMinimumSize(QtCore.QSize(450, 80))
        self.label.setMaximumSize(QtCore.QSize(16777215, 100))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.label_2.setMinimumSize(QtCore.QSize(450, 0))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignHCenter|QtCore.Qt.AlignmentFlag.AlignTop)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 2, 1, 1)
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setContentsMargins(20, -1, 20, -1)
        self.formLayout.setSpacing(20)
        self.formLayout.setObjectName("formLayout")
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_4)
        self.passwordType = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        self.passwordType.setObjectName("passwordType")
        self.passwordType.addItem("")
        self.passwordType.addItem("")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.FieldRole, self.passwordType)
        self.label_5 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_5)
        self.passwordLength = QtWidgets.QSpinBox(parent=self.gridLayoutWidget)
        self.passwordLength.setObjectName("passwordLength")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.FieldRole, self.passwordLength)
        self.label_6 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.label_6)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.specialChar = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.specialChar.setObjectName("specialChar")
        self.verticalLayout.addWidget(self.specialChar)
        self.numbers = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.numbers.setObjectName("numbers")
        self.verticalLayout.addWidget(self.numbers)
        self.capitalChars = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.capitalChars.setObjectName("capitalChars")
        self.verticalLayout.addWidget(self.capitalChars)
        self.easter = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.easter.setObjectName("easter")
        self.verticalLayout.addWidget(self.easter)
        self.word = QtWidgets.QCheckBox(parent=self.gridLayoutWidget)
        self.word.setObjectName("word")
        self.verticalLayout.addWidget(self.word)
        self.formLayout.setLayout(2, QtWidgets.QFormLayout.ItemRole.FieldRole, self.verticalLayout)
        self.generate = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.generate.setObjectName("generate")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.generate)
        self.gridLayout.addLayout(self.formLayout, 2, 0, 1, 1)
        self.image = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.image.setText("")
        self.image.setObjectName("image")
        self.gridLayout.addWidget(self.image, 3, 2, 1, 1)
        self.genertedPassword = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        self.genertedPassword.setText("")
        self.genertedPassword.setScaledContents(True)
        self.genertedPassword.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.genertedPassword.setWordWrap(False)
        self.genertedPassword.setObjectName("genertedPassword")
        self.gridLayout.addWidget(self.genertedPassword, 3, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "Hasło"))
        self.label_7.setText(_translate("Dialog", "Moc hasła"))
        self.label.setText(_translate("Dialog", "Generowanie hasła"))
        self.label_2.setText(_translate("Dialog", "Sprawdzanie hasła"))
        self.label_4.setText(_translate("Dialog", "Typ hasła"))
        self.passwordType.setItemText(0, _translate("Dialog", "Hasło"))
        self.passwordType.setItemText(1, _translate("Dialog", "Pin"))
        self.label_5.setText(_translate("Dialog", "Długość"))
        self.label_6.setText(_translate("Dialog", "Wymagania"))
        self.specialChar.setText(_translate("Dialog", "Znaki specjalne"))
        self.numbers.setText(_translate("Dialog", "Cyfry"))
        self.capitalChars.setText(_translate("Dialog", "Duże litery"))
        self.easter.setText(_translate("Dialog", "Zając wielkanocny"))
        self.word.setText(_translate("Dialog", "Słowo"))
        self.generate.setText(_translate("Dialog", "Generuj"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
